export interface EmojiStatic {
  char: string
  name: string
  shortcode: string
  category?: string
  keywords?: string[]
}

// Curated static emoji list. Categories are canonical keys used by the UI
// (smileys, people, animals, food, activities, travel, objects, symbols,
// flags, nature). This list is intentionally curated for fast UI and can be
// extended or replaced by a full dataset in `public/emoji-full.json` if needed.
export const STATIC_EMOJIS: EmojiStatic[] = [
  // Smileys & Emotion (expanded)
  { char: '😀', name: 'Grinning Face', shortcode: ':grinning:', category: 'smileys', keywords: ['happy', 'smile'] },
  { char: '😃', name: 'Grinning Face With Big Eyes', shortcode: ':smiley:', category: 'smileys' },
  { char: '😄', name: 'Grinning Face With Smiling Eyes', shortcode: ':smile:', category: 'smileys' },
  { char: '😁', name: 'Beaming Face With Smiling Eyes', shortcode: ':grin:', category: 'smileys' },
  { char: '😆', name: 'Grinning Squinting Face', shortcode: ':laughing:', category: 'smileys' },
  { char: '😅', name: 'Grinning Face With Sweat', shortcode: ':sweat_smile:', category: 'smileys' },
  { char: '🤣', name: 'Rolling on the Floor Laughing', shortcode: ':rofl:', category: 'smileys' },
  { char: '😂', name: 'Face With Tears of Joy', shortcode: ':joy:', category: 'smileys' },
  { char: '🙂', name: 'Slightly Smiling Face', shortcode: ':slightly_smiling_face:', category: 'smileys' },
  { char: '🙃', name: 'Upside-Down Face', shortcode: ':upside_down:', category: 'smileys' },
  { char: '😉', name: 'Winking Face', shortcode: ':wink:', category: 'smileys' },
  { char: '😊', name: 'Smiling Face With Smiling Eyes', shortcode: ':blush:', category: 'smileys' },
  { char: '😇', name: 'Smiling Face with Halo', shortcode: ':innocent:', category: 'smileys' },
  { char: '🥰', name: 'Smiling Face with Hearts', shortcode: ':smiling_face_with_three_hearts:', category: 'smileys' },
  { char: '😍', name: 'Smiling Face With Heart-Eyes', shortcode: ':heart_eyes:', category: 'smileys' },
  { char: '🤩', name: 'Star-Struck', shortcode: ':star_struck:', category: 'smileys' },
  { char: '😘', name: 'Face Blowing a Kiss', shortcode: ':kissing_heart:', category: 'smileys' },
  { char: '😗', name: 'Kissing Face', shortcode: ':kissing:', category: 'smileys' },
  { char: '😚', name: 'Kissing Face With Closed Eyes', shortcode: ':kissing_closed_eyes:', category: 'smileys' },
  { char: '😙', name: 'Kissing Face With Smiling Eyes', shortcode: ':kissing_smiling_eyes:', category: 'smileys' },
  { char: '😋', name: 'Face Savoring Food', shortcode: ':yum:', category: 'smileys' },
  { char: '😛', name: 'Face With Tongue', shortcode: ':stuck_out_tongue:', category: 'smileys' },
  { char: '😜', name: 'Winking Face With Tongue', shortcode: ':stuck_out_tongue_winking_eye:', category: 'smileys' },
  { char: '🤪', name: 'Zany Face', shortcode: ':zany_face:', category: 'smileys' },
  { char: '😝', name: 'Squinting Face With Tongue', shortcode: ':stuck_out_tongue_closed_eyes:', category: 'smileys' },
  { char: '🤫', name: 'Shushing Face', shortcode: ':shushing_face:', category: 'smileys' },
  { char: '🤔', name: 'Thinking Face', shortcode: ':thinking:', category: 'smileys' },
  { char: '🤨', name: 'Face With Raised Eyebrow', shortcode: ':raised_eyebrow:', category: 'smileys' },
  { char: '😐', name: 'Neutral Face', shortcode: ':neutral_face:', category: 'smileys' },
  { char: '😑', name: 'Expressionless Face', shortcode: ':expressionless:', category: 'smileys' },
  { char: '😶', name: 'Face Without Mouth', shortcode: ':no_mouth:', category: 'smileys' },
  { char: '😏', name: 'Smirking Face', shortcode: ':smirk:', category: 'smileys' },
  { char: '😒', name: 'Unamused Face', shortcode: ':unamused:', category: 'smileys' },
  { char: '🙄', name: 'Face with Rolling Eyes', shortcode: ':rolling_eyes:', category: 'smileys' },
  { char: '😬', name: 'Grimacing Face', shortcode: ':grimacing:', category: 'smileys' },
  { char: '🤥', name: 'Lying Face', shortcode: ':lying_face:', category: 'smileys' },
  { char: '😌', name: 'Relieved Face', shortcode: ':relieved:', category: 'smileys' },
  { char: '😔', name: 'Pensive Face', shortcode: ':pensive:', category: 'smileys' },
  { char: '😪', name: 'Sleepy Face', shortcode: ':sleepy:', category: 'smileys' },
  { char: '🤤', name: 'Drooling Face', shortcode: ':drooling_face:', category: 'smileys' },
  { char: '😴', name: 'Sleeping Face', shortcode: ':sleeping:', category: 'smileys' },
  { char: '😷', name: 'Face with Medical Mask', shortcode: ':mask:', category: 'smileys' },
  { char: '🤒', name: 'Face with Thermometer', shortcode: ':face_with_thermometer:', category: 'smileys' },
  { char: '🤕', name: 'Face with Head-Bandage', shortcode: ':face_with_head_bandage:', category: 'smileys' },
  { char: '🤢', name: 'Nauseated Face', shortcode: ':nauseated_face:', category: 'smileys' },
  { char: '🤮', name: 'Face Vomiting', shortcode: ':vomiting_face:', category: 'smileys' },
  { char: '🤧', name: 'Sneezing Face', shortcode: ':sneezing_face:', category: 'smileys' },
  { char: '🥵', name: 'Hot Face', shortcode: ':hot_face:', category: 'smileys' },
  { char: '🥶', name: 'Cold Face', shortcode: ':cold_face:', category: 'smileys' },
  { char: '🥴', name: 'Woozy Face', shortcode: ':woozy_face:', category: 'smileys' },
  { char: '😵', name: 'Dizzy Face', shortcode: ':dizzy_face:', category: 'smileys' },
  { char: '🤯', name: 'Exploding Head', shortcode: ':exploding_head:', category: 'smileys' },
  { char: '🤠', name: 'Cowboy Hat Face', shortcode: ':cowboy_hat_face:', category: 'smileys' },
  { char: '🥳', name: 'Partying Face', shortcode: ':partying_face:', category: 'smileys' },
  { char: '😎', name: 'Smiling Face With Sunglasses', shortcode: ':sunglasses:', category: 'smileys' },
  { char: '🤓', name: 'Nerd Face', shortcode: ':nerd_face:', category: 'smileys' },
  { char: '🧐', name: 'Face With Monocle', shortcode: ':monocle_face:', category: 'smileys' },
  { char: '😕', name: 'Confused Face', shortcode: ':confused:', category: 'smileys' },
  { char: '😟', name: 'Worried Face', shortcode: ':worried:', category: 'smileys' },
  { char: '🙁', name: 'Slightly Frowning Face', shortcode: ':slightly_frowning_face:', category: 'smileys' },
  { char: '☹️', name: 'Frowning Face', shortcode: ':frowning_face:', category: 'smileys' },
  { char: '😮', name: 'Face With Open Mouth', shortcode: ':open_mouth:', category: 'smileys' },
  { char: '😯', name: 'Hushed Face', shortcode: ':hushed:', category: 'smileys' },
  { char: '😲', name: 'Astonished Face', shortcode: ':astonished:', category: 'smileys' },
  { char: '😳', name: 'Flushed Face', shortcode: ':flushed:', category: 'smileys' },
  { char: '🥺', name: 'Pleading Face', shortcode: ':pleading_face:', category: 'smileys' },
  { char: '😦', name: 'Frowning Face with Open Mouth', shortcode: ':frowning:', category: 'smileys' },
  { char: '😧', name: 'Anguished Face', shortcode: ':anguished:', category: 'smileys' },
  { char: '😨', name: 'Fearful Face', shortcode: ':fearful:', category: 'smileys' },
  { char: '😰', name: 'Anxious Face with Sweat', shortcode: ':cold_sweat:', category: 'smileys' },
  { char: '😥', name: 'Sad but Relieved Face', shortcode: ':disappointed_relieved:', category: 'smileys' },
  { char: '😢', name: 'Crying Face', shortcode: ':cry:', category: 'smileys' },
  { char: '😭', name: 'Loudly Crying Face', shortcode: ':sob:', category: 'smileys' },
  { char: '😱', name: 'Face Screaming in Fear', shortcode: ':scream:', category: 'smileys' },
  { char: '😖', name: 'Confounded Face', shortcode: ':confounded:', category: 'smileys' },
  { char: '😣', name: 'Persevering Face', shortcode: ':persevere:', category: 'smileys' },
  { char: '😞', name: 'Disappointed Face', shortcode: ':disappointed:', category: 'smileys' },
  { char: '😓', name: 'Downcast Face with Sweat', shortcode: ':sweat:', category: 'smileys' },
  { char: '😩', name: 'Weary Face', shortcode: ':weary:', category: 'smileys' },
  { char: '😫', name: 'Tired Face', shortcode: ':tired_face:', category: 'smileys' },
  { char: '🥱', name: 'Yawning Face', shortcode: ':yawning_face:', category: 'smileys' },
  { char: '😤', name: 'Face with Steam From Nose', shortcode: ':triumph:', category: 'smileys' },
  { char: '😠', name: 'Angry Face', shortcode: ':angry:', category: 'smileys' },
  { char: '😡', name: 'Pouting Face', shortcode: ':pouting_face:', category: 'smileys' },
  { char: '🤬', name: 'Face with Symbols on Mouth', shortcode: ':face_with_symbols_on_mouth:', category: 'smileys' },
  { char: '😈', name: 'Smiling Face with Horns', shortcode: ':smiling_imp:', category: 'smileys' },
  { char: '👿', name: 'Angry Face with Horns', shortcode: ':imp:', category: 'smileys' },
  { char: '💀', name: 'Skull', shortcode: ':skull:', category: 'smileys' },
  { char: '💩', name: 'Pile of Poo', shortcode: ':poop:', category: 'smileys' },
  { char: '🤡', name: 'Clown Face', shortcode: ':clown_face:', category: 'smileys' },
  { char: '👻', name: 'Ghost', shortcode: ':ghost:', category: 'smileys' },
  { char: '👽', name: 'Alien', shortcode: ':alien:', category: 'smileys' },
  { char: '🤖', name: 'Robot', shortcode: ':robot:', category: 'smileys' },
  { char: '🎃', name: 'Jack-O-Lantern', shortcode: ':jack_o_lantern:', category: 'smileys' },
  { char: '😺', name: 'Grinning Cat', shortcode: ':smiley_cat:', category: 'smileys' },
  { char: '😸', name: 'Grinning Cat with Smiling Eyes', shortcode: ':smile_cat:', category: 'smileys' },
  { char: '😹', name: 'Cat with Tears of Joy', shortcode: ':joy_cat:', category: 'smileys' },
  { char: '😻', name: 'Smiling Cat with Heart-Eyes', shortcode: ':heart_eyes_cat:', category: 'smileys' },
  { char: '😼', name: 'Cat with Wry Smile', shortcode: ':smirk_cat:', category: 'smileys' },
  { char: '😽', name: 'Kissing Cat', shortcode: ':kissing_cat:', category: 'smileys' },
  { char: '🙀', name: 'Weary Cat', shortcode: ':scream_cat:', category: 'smileys' },
  { char: '😿', name: 'Crying Cat', shortcode: ':crying_cat_face:', category: 'smileys' },
  { char: '😾', name: 'Pouting Cat', shortcode: ':pouting_cat:', category: 'smileys' },
  { char: '🤗', name: 'Hugging Face', shortcode: ':hugs:', category: 'smileys' },

  // People & Body (expanded)
  { char: '👋', name: 'Waving Hand', shortcode: ':wave:', category: 'people' },
  { char: '🤚', name: 'Raised Back of Hand', shortcode: ':raised_back_of_hand:', category: 'people' },
  { char: '🖐️', name: 'Hand with Fingers Splayed', shortcode: ':hand_with_fingers_splayed:', category: 'people' },
  { char: '✋', name: 'Raised Hand', shortcode: ':raised_hand:', category: 'people' },
  { char: '🖖', name: 'Vulcan Salute', shortcode: ':vulcan_salute:', category: 'people' },
  { char: '👌', name: 'OK Hand', shortcode: ':ok_hand:', category: 'people' },
  { char: '🤌', name: 'Pinched Fingers', shortcode: ':pinched_fingers:', category: 'people' },
  { char: '🤏', name: 'Pinching Hand', shortcode: ':pinching_hand:', category: 'people' },
  { char: '✌️', name: 'Victory Hand', shortcode: ':v:', category: 'people' },
  { char: '🤞', name: 'Crossed Fingers', shortcode: ':crossed_fingers:', category: 'people' },
  { char: '🤟', name: 'Love-You Gesture', shortcode: ':love_you_gesture:', category: 'people' },
  { char: '🤘', name: 'Sign of the Horns', shortcode: ':metal:', category: 'people' },
  { char: '🤙', name: 'Call Me Hand', shortcode: ':call_me_hand:', category: 'people' },
  { char: '👈', name: 'Backhand Index Pointing Left', shortcode: ':point_left:', category: 'people' },
  { char: '👉', name: 'Backhand Index Pointing Right', shortcode: ':point_right:', category: 'people' },
  { char: '👆', name: 'Backhand Index Pointing Up', shortcode: ':point_up_2:', category: 'people' },
  { char: '🖕', name: 'Middle Finger', shortcode: ':middle_finger:', category: 'people' },
  { char: '👇', name: 'Backhand Index Pointing Down', shortcode: ':point_down:', category: 'people' },
  { char: '👍', name: 'Thumbs Up', shortcode: ':thumbsup:', category: 'people' },
  { char: '👎', name: 'Thumbs Down', shortcode: ':thumbsdown:', category: 'people' },
  { char: '✊', name: 'Raised Fist', shortcode: ':fist:', category: 'people' },
  { char: '👊', name: 'Oncoming Fist', shortcode: ':facepunch:', category: 'people' },
  { char: '🤛', name: 'Left-Facing Fist', shortcode: ':left_facing_fist:', category: 'people' },
  { char: '🤜', name: 'Right-Facing Fist', shortcode: ':right_facing_fist:', category: 'people' },
  { char: '👏', name: 'Clapping Hands', shortcode: ':clap:', category: 'people' },
  { char: '🙌', name: 'Raising Hands', shortcode: ':raised_hands:', category: 'people' },
  { char: '👐', name: 'Open Hands', shortcode: ':open_hands:', category: 'people' },
  { char: '🤝', name: 'Handshake', shortcode: ':handshake:', category: 'people' },
  { char: '🙏', name: 'Folded Hands', shortcode: ':pray:', category: 'people' },
  { char: '✍️', name: 'Writing Hand', shortcode: ':writing_hand:', category: 'people' },
  { char: '💅', name: 'Nail Polish', shortcode: ':nail_care:', category: 'people' },
  { char: '🤳', name: 'Selfie', shortcode: ':selfie:', category: 'people' },
  { char: '💪', name: 'Flexed Biceps', shortcode: ':muscle:', category: 'people' },
  { char: '🦾', name: 'Mechanical Arm', shortcode: ':mechanical_arm:', category: 'people' },
  { char: '🦵', name: 'Leg', shortcode: ':leg:', category: 'people' },
  { char: '🦶', name: 'Foot', shortcode: ':foot:', category: 'people' },
  { char: '👂', name: 'Ear', shortcode: ':ear:', category: 'people' },
  { char: '👃', name: 'Nose', shortcode: ':nose:', category: 'people' },
  { char: '🧠', name: 'Brain', shortcode: ':brain:', category: 'people' },
  { char: '🦷', name: 'Tooth', shortcode: ':tooth:', category: 'people' },
  { char: '🦴', name: 'Bone', shortcode: ':bone:', category: 'people' },
  { char: '👀', name: 'Eyes', shortcode: ':eyes:', category: 'people' },
  { char: '👁️', name: 'Eye', shortcode: ':eye:', category: 'people' },
  { char: '👅', name: 'Tongue', shortcode: ':tongue:', category: 'people' },
  { char: '👄', name: 'Mouth', shortcode: ':lips:', category: 'people' },
  { char: '👶', name: 'Baby', shortcode: ':baby:', category: 'people' },
  { char: '🧒', name: 'Child', shortcode: ':child:', category: 'people' },
  { char: '👦', name: 'Boy', shortcode: ':boy:', category: 'people' },
  { char: '👧', name: 'Girl', shortcode: ':girl:', category: 'people' },
  { char: '🧑', name: 'Person', shortcode: ':person:', category: 'people' },
  { char: '👱', name: 'Person: Blond Hair', shortcode: ':person_with_blond_hair:', category: 'people' },
  { char: '👨', name: 'Man', shortcode: ':man:', category: 'people' },
  { char: '🧔', name: 'Person: Beard', shortcode: ':bearded_person:', category: 'people' },
  { char: '👩', name: 'Woman', shortcode: ':woman:', category: 'people' },
  { char: '🧓', name: 'Older Person', shortcode: ':older_adult:', category: 'people' },
  { char: '👴', name: 'Old Man', shortcode: ':older_man:', category: 'people' },
  { char: '👵', name: 'Old Woman', shortcode: ':older_woman:', category: 'people' },
  { char: '👮', name: 'Police Officer', shortcode: ':police_officer:', category: 'people' },
  { char: '👷', name: 'Construction Worker', shortcode: ':construction_worker:', category: 'people' },
  { char: '💂', name: 'Guard', shortcode: ':guard:', category: 'people' },
  { char: '🕵️', name: 'Detective', shortcode: ':detective:', category: 'people' },
  { char: '👩‍⚕️', name: 'Health Worker', shortcode: ':health_worker:', category: 'people' },
  { char: '👨‍🌾', name: 'Farmer', shortcode: ':farmer:', category: 'people' },
  { char: '👨‍🍳', name: 'Cook', shortcode: ':cook:', category: 'people' },
  { char: '👨‍🎓', name: 'Student', shortcode: ':student:', category: 'people' },
  { char: '👨‍🎤', name: 'Singer', shortcode: ':singer:', category: 'people' },
  { char: '👨‍🏫', name: 'Teacher', shortcode: ':teacher:', category: 'people' },
  { char: '👨‍🏭', name: 'Factory Worker', shortcode: ':factory_worker:', category: 'people' },
  { char: '👨‍💻', name: 'Technologist', shortcode: ':technologist:', category: 'people' },
  { char: '👨‍💼', name: 'Office Worker', shortcode: ':office_worker:', category: 'people' },
  { char: '👨‍🔧', name: 'Mechanic', shortcode: ':mechanic:', category: 'people' },
  { char: '👨‍🔬', name: 'Scientist', shortcode: ':scientist:', category: 'people' },
  { char: '👨‍🎨', name: 'Artist', shortcode: ':artist:', category: 'people' },
  { char: '👨‍🚒', name: 'Firefighter', shortcode: ':firefighter:', category: 'people' },
  { char: '👨‍✈️', name: 'Pilot', shortcode: ':pilot:', category: 'people' },
  { char: '👨‍🚀', name: 'Astronaut', shortcode: ':astronaut:', category: 'people' },
  { char: '👨‍⚖️', name: 'Judge', shortcode: ':judge:', category: 'people' },
  { char: '🤴', name: 'Prince', shortcode: ':prince:', category: 'people' },
  { char: '👸', name: 'Princess', shortcode: ':princess:', category: 'people' },
  { char: '🦸', name: 'Superhero', shortcode: ':superhero:', category: 'people' },
  { char: '🦹', name: 'Supervillain', shortcode: ':supervillain:', category: 'people' },
  { char: '🧙', name: 'Mage', shortcode: ':mage:', category: 'people' },
  { char: '🧝', name: 'Elf', shortcode: ':elf:', category: 'people' },
  { char: '🧛', name: 'Vampire', shortcode: ':vampire:', category: 'people' },
  { char: '🧟', name: 'Zombie', shortcode: ':zombie:', category: 'people' },
  { char: '🧞', name: 'Genie', shortcode: ':genie:', category: 'people' },
  { char: '🧜', name: 'Merperson', shortcode: ':merperson:', category: 'people' },
  { char: '🧚', name: 'Fairy', shortcode: ':fairy:', category: 'people' },
  { char: '💃', name: 'Woman Dancing', shortcode: ':dancer:', category: 'people' },
  { char: '🕺', name: 'Man Dancing', shortcode: ':man_dancing:', category: 'people' },
  { char: '👯', name: 'People with Bunny Ears', shortcode: ':dancers:', category: 'people' },
  { char: '🚶', name: 'Person Walking', shortcode: ':walking:', category: 'people' },
  { char: '🏃', name: 'Person Running', shortcode: ':runner:', category: 'people' },
  { char: '🗣️', name: 'Speaking Head', shortcode: ':speaking_head:', category: 'people' },
  { char: '👣', name: 'Footprints', shortcode: ':footprints:', category: 'people' },

  // Animals & Nature (expanded)
  { char: '🐵', name: 'Monkey Face', shortcode: ':monkey_face:', category: 'animals' },
  { char: '🐒', name: 'Monkey', shortcode: ':monkey:', category: 'animals' },
  { char: '🦍', name: 'Gorilla', shortcode: ':gorilla:', category: 'animals' },
  { char: '🦧', name: 'Orangutan', shortcode: ':orangutan:', category: 'animals' },
  { char: '🐶', name: 'Dog Face', shortcode: ':dog:', category: 'animals' },
  { char: '🐕', name: 'Dog', shortcode: ':dog2:', category: 'animals' },
  { char: '🐩', name: 'Poodle', shortcode: ':poodle:', category: 'animals' },
  { char: '🐺', name: 'Wolf', shortcode: ':wolf:', category: 'animals' },
  { char: '🦊', name: 'Fox', shortcode: ':fox_face:', category: 'animals' },
  { char: '🦝', name: 'Raccoon', shortcode: ':raccoon:', category: 'animals' },
  { char: '🐱', name: 'Cat Face', shortcode: ':cat:', category: 'animals' },
  { char: '🐈', name: 'Cat', shortcode: ':cat2:', category: 'animals' },
  { char: '🦁', name: 'Lion', shortcode: ':lion_face:', category: 'animals' },
  { char: '🐯', name: 'Tiger Face', shortcode: ':tiger:', category: 'animals' },
  { char: '🐅', name: 'Tiger', shortcode: ':tiger2:', category: 'animals' },
  { char: '🐆', name: 'Leopard', shortcode: ':leopard:', category: 'animals' },
  { char: '🐴', name: 'Horse Face', shortcode: ':horse:', category: 'animals' },
  { char: '🦄', name: 'Unicorn', shortcode: ':unicorn:', category: 'animals' },
  { char: '🦓', name: 'Zebra', shortcode: ':zebra:', category: 'animals' },
  { char: '🐮', name: 'Cow Face', shortcode: ':cow:', category: 'animals' },
  { char: '🐷', name: 'Pig Face', shortcode: ':pig:', category: 'animals' },
  { char: '🐗', name: 'Boar', shortcode: ':boar:', category: 'animals' },
  { char: '🐘', name: 'Elephant', shortcode: ':elephant:', category: 'animals' },
  { char: '🐼', name: 'Panda', shortcode: ':panda_face:', category: 'animals' },
  { char: '🐻', name: 'Bear', shortcode: ':bear:', category: 'animals' },
  { char: '🐨', name: 'Koala', shortcode: ':koala:', category: 'animals' },
  { char: '🐰', name: 'Rabbit Face', shortcode: ':rabbit:', category: 'animals' },
  { char: '🐇', name: 'Rabbit', shortcode: ':rabbit2:', category: 'animals' },
  { char: '🐹', name: 'Hamster', shortcode: ':hamster:', category: 'animals' },
  { char: '🐭', name: 'Mouse Face', shortcode: ':mouse:', category: 'animals' },
  { char: '🦇', name: 'Bat', shortcode: ':bat:', category: 'animals' },
  { char: '🐔', name: 'Chicken', shortcode: ':chicken:', category: 'animals' },
  { char: '🐧', name: 'Penguin', shortcode: ':penguin:', category: 'animals' },
  { char: '🐦', name: 'Bird', shortcode: ':bird:', category: 'animals' },
  { char: '🐸', name: 'Frog Face', shortcode: ':frog:', category: 'animals' },
  { char: '🐢', name: 'Turtle', shortcode: ':turtle:', category: 'animals' },
  { char: '🐍', name: 'Snake', shortcode: ':snake:', category: 'animals' },
  { char: '🦎', name: 'Lizard', shortcode: ':lizard:', category: 'animals' },
  { char: '🦖', name: 'T-Rex', shortcode: ':t-rex:', category: 'animals' },
  { char: '🦕', name: 'Sauropod', shortcode: ':sauropod:', category: 'animals' },
  { char: '🐳', name: 'Spouting Whale', shortcode: ':whale:', category: 'animals' },
  { char: '🐬', name: 'Dolphin', shortcode: ':dolphin:', category: 'animals' },
  { char: '🐠', name: 'Tropical Fish', shortcode: ':tropical_fish:', category: 'animals' },
  { char: '🐙', name: 'Octopus', shortcode: ':octopus:', category: 'animals' },
  { char: '🦈', name: 'Shark', shortcode: ':shark:', category: 'animals' },
  { char: '🦋', name: 'Butterfly', shortcode: ':butterfly:', category: 'animals' },
  { char: '🐛', name: 'Bug', shortcode: ':bug:', category: 'animals' },
  { char: '🐜', name: 'Ant', shortcode: ':ant:', category: 'animals' },
  { char: '🐝', name: 'Honeybee', shortcode: ':bee:', category: 'animals' },
  { char: '🐞', name: 'Lady Beetle', shortcode: ':lady_beetle:', category: 'animals' },
  { char: '🦗', name: 'Cricket', shortcode: ':cricket:', category: 'animals' },
  { char: '🕷️', name: 'Spider', shortcode: ':spider:', category: 'animals' },
  { char: '🦂', name: 'Scorpion', shortcode: ':scorpion:', category: 'animals' },
  { char: '💐', name: 'Bouquet', shortcode: ':bouquet:', category: 'nature' },
  { char: '🌸', name: 'Cherry Blossom', shortcode: ':cherry_blossom:', category: 'nature' },
  { char: '💮', name: 'White Flower', shortcode: ':white_flower:', category: 'nature' },
  { char: '🌹', name: 'Rose', shortcode: ':rose:', category: 'nature' },
  { char: '🥀', name: 'Wilted Flower', shortcode: ':wilted_flower:', category: 'nature' },
  { char: '🌺', name: 'Hibiscus', shortcode: ':hibiscus:', category: 'nature' },
  { char: '🌻', name: 'Sunflower', shortcode: ':sunflower:', category: 'nature' },
  { char: '🌼', name: 'Blossom', shortcode: ':blossom:', category: 'nature' },
  { char: '🌷', name: 'Tulip', shortcode: ':tulip:', category: 'nature' },
  { char: '🌱', name: 'Seedling', shortcode: ':seedling:', category: 'nature' },
  { char: '🌲', name: 'Evergreen Tree', shortcode: ':evergreen_tree:', category: 'nature' },
  { char: '🌳', name: 'Deciduous Tree', shortcode: ':deciduous_tree:', category: 'nature' },
  { char: '🌴', name: 'Palm Tree', shortcode: ':palm_tree:', category: 'nature' },
  { char: '🌵', name: 'Cactus', shortcode: ':cactus:', category: 'nature' },
  { char: '🍁', name: 'Maple Leaf', shortcode: ':maple_leaf:', category: 'nature' },
  { char: '🍂', name: 'Fallen Leaf', shortcode: ':fallen_leaf:', category: 'nature' },
  { char: '🍃', name: 'Leaf Fluttering in Wind', shortcode: ':leaves:', category: 'nature' },
  { char: '🌍', name: 'Earth Globe Europe-Africa', shortcode: ':earth_africa:', category: 'nature' },
  { char: '🌞', name: 'Sun With Face', shortcode: ':sun_with_face:', category: 'nature' },
  { char: '🌕', name: 'Full Moon Face', shortcode: ':full_moon_with_face:', category: 'nature' },
  { char: '🌙', name: 'Crescent Moon', shortcode: ':crescent_moon:', category: 'nature' },
  { char: '⭐', name: 'Star', shortcode: ':star:', category: 'nature' },
  { char: '🌟', name: 'Glowing Star', shortcode: ':star2:', category: 'nature' },
  { char: '☁️', name: 'Cloud', shortcode: ':cloud:', category: 'nature' },
  { char: '⚡', name: 'High Voltage', shortcode: ':zap:', category: 'nature' },
  { char: '🔥', name: 'Fire', shortcode: ':fire:', category: 'symbols' },
  { char: '💧', name: 'Droplet', shortcode: ':droplet:', category: 'nature' },
  { char: '🌊', name: 'Water Wave', shortcode: ':ocean:', category: 'nature' },
  { char: '🌈', name: 'Rainbow', shortcode: ':rainbow:', category: 'nature' },
  { char: '🌋', name: 'Volcano', shortcode: ':volcano:', category: 'nature' },

  // Food & Drink (expanded)
  { char: '🍇', name: 'Grapes', shortcode: ':grapes:', category: 'food' },
  { char: '🍈', name: 'Melon', shortcode: ':melon:', category: 'food' },
  { char: '🍉', name: 'Watermelon', shortcode: ':watermelon:', category: 'food' },
  { char: '🍊', name: 'Tangerine', shortcode: ':tangerine:', category: 'food' },
  { char: '🍋', name: 'Lemon', shortcode: ':lemon:', category: 'food' },
  { char: '🍌', name: 'Banana', shortcode: ':banana:', category: 'food' },
  { char: '🍍', name: 'Pineapple', shortcode: ':pineapple:', category: 'food' },
  { char: '🥭', name: 'Mango', shortcode: ':mango:', category: 'food' },
  { char: '🍎', name: 'Red Apple', shortcode: ':apple:', category: 'food' },
  { char: '🍏', name: 'Green Apple', shortcode: ':green_apple:', category: 'food' },
  { char: '🍐', name: 'Pear', shortcode: ':pear:', category: 'food' },
  { char: '🍑', name: 'Peach', shortcode: ':peach:', category: 'food' },
  { char: '🍒', name: 'Cherries', shortcode: ':cherries:', category: 'food' },
  { char: '🍓', name: 'Strawberry', shortcode: ':strawberry:', category: 'food' },
  { char: '🥝', name: 'Kiwi Fruit', shortcode: ':kiwi_fruit:', category: 'food' },
  { char: '🍅', name: 'Tomato', shortcode: ':tomato:', category: 'food' },
  { char: '🥥', name: 'Coconut', shortcode: ':coconut:', category: 'food' },
  { char: '🥑', name: 'Avocado', shortcode: ':avocado:', category: 'food' },
  { char: '🍆', name: 'Eggplant', shortcode: ':eggplant:', category: 'food' },
  { char: '🥔', name: 'Potato', shortcode: ':potato:', category: 'food' },
  { char: '🥕', name: 'Carrot', shortcode: ':carrot:', category: 'food' },
  { char: '🌽', name: 'Ear of Corn', shortcode: ':corn:', category: 'food' },
  { char: '🌶️', name: 'Hot Pepper', shortcode: ':hot_pepper:', category: 'food' },
  { char: '🥒', name: 'Cucumber', shortcode: ':cucumber:', category: 'food' },
  { char: '🥦', name: 'Broccoli', shortcode: ':broccoli:', category: 'food' },
  { char: '🍄', name: 'Mushroom', shortcode: ':mushroom:', category: 'food' },
  { char: '🥜', name: 'Peanuts', shortcode: ':peanuts:', category: 'food' },
  { char: '🍞', name: 'Bread', shortcode: ':bread:', category: 'food' },
  { char: '🥐', name: 'Croissant', shortcode: ':croissant:', category: 'food' },
  { char: '🥖', name: 'Baguette Bread', shortcode: ':baguette_bread:', category: 'food' },
  { char: '🥨', name: 'Pretzel', shortcode: ':pretzel:', category: 'food' },
  { char: '🥯', name: 'Bagel', shortcode: ':bagel:', category: 'food' },
  { char: '🥞', name: 'Pancakes', shortcode: ':pancakes:', category: 'food' },
  { char: '🧇', name: 'Waffle', shortcode: ':waffle:', category: 'food' },
  { char: '🧀', name: 'Cheese Wedge', shortcode: ':cheese:', category: 'food' },
  { char: '🍖', name: 'Meat on Bone', shortcode: ':meat_on_bone:', category: 'food' },
  { char: '🍗', name: 'Poultry Leg', shortcode: ':poultry_leg:', category: 'food' },
  { char: '🥩', name: 'Cut of Meat', shortcode: ':cut_of_meat:', category: 'food' },
  { char: '🥓', name: 'Bacon', shortcode: ':bacon:', category: 'food' },
  { char: '🍔', name: 'Hamburger', shortcode: ':hamburger:', category: 'food' },
  { char: '🍟', name: 'French Fries', shortcode: ':fries:', category: 'food' },
  { char: '🍕', name: 'Pizza', shortcode: ':pizza:', category: 'food' },
  { char: '🌭', name: 'Hot Dog', shortcode: ':hotdog:', category: 'food' },
  { char: '🥪', name: 'Sandwich', shortcode: ':sandwich:', category: 'food' },
  { char: '🌮', name: 'Taco', shortcode: ':taco:', category: 'food' },
  { char: '🌯', name: 'Burrito', shortcode: ':burrito:', category: 'food' },
  { char: '🍳', name: 'Cooking', shortcode: ':egg:', category: 'food' },
  { char: '🍲', name: 'Pot of Food', shortcode: ':stew:', category: 'food' },
  { char: '🍜', name: 'Steaming Bowl', shortcode: ':ramen:', category: 'food' },
  { char: '🍝', name: 'Spaghetti', shortcode: ':spaghetti:', category: 'food' },
  { char: '🍣', name: 'Sushi', shortcode: ':sushi:', category: 'food' },
  { char: '🍱', name: 'Bento Box', shortcode: ':bento:', category: 'food' },
  { char: '🍚', name: 'Cooked Rice', shortcode: ':rice:', category: 'food' },
  { char: '🍦', name: 'Soft Ice Cream', shortcode: ':icecream:', category: 'food' },
  { char: '🍧', name: 'Shaved Ice', shortcode: ':shaved_ice:', category: 'food' },
  { char: '🍨', name: 'Ice Cream', shortcode: ':ice_cream:', category: 'food' },
  { char: '🍩', name: 'Doughnut', shortcode: ':doughnut:', category: 'food' },
  { char: '🍪', name: 'Cookie', shortcode: ':cookie:', category: 'food' },
  { char: '🎂', name: 'Birthday Cake', shortcode: ':birthday:', category: 'food' },
  { char: '🍰', name: 'Shortcake', shortcode: ':cake:', category: 'food' },
  { char: '🧁', name: 'Cupcake', shortcode: ':cupcake:', category: 'food' },
  { char: '🥧', name: 'Pie', shortcode: ':pie:', category: 'food' },
  { char: '🍫', name: 'Chocolate Bar', shortcode: ':chocolate_bar:', category: 'food' },
  { char: '🍬', name: 'Candy', shortcode: ':candy:', category: 'food' },
  { char: '🍭', name: 'Lollipop', shortcode: ':lollipop:', category: 'food' },
  { char: '🍮', name: 'Custard', shortcode: ':custard:', category: 'food' },
  { char: '🍯', name: 'Honey Pot', shortcode: ':honey_pot:', category: 'food' },
  { char: '☕', name: 'Hot Beverage', shortcode: ':coffee:', category: 'food' },
  { char: '🍵', name: 'Teacup Without Handle', shortcode: ':tea:', category: 'food' },
  { char: '🍶', name: 'Sake', shortcode: ':sake:', category: 'food' },
  { char: '🍾', name: 'Bottle with Popping Cork', shortcode: ':champagne:', category: 'food' },
  { char: '🍷', name: 'Wine Glass', shortcode: ':wine_glass:', category: 'food' },
  { char: '🍸', name: 'Cocktail Glass', shortcode: ':cocktail:', category: 'food' },
  { char: '🍹', name: 'Tropical Drink', shortcode: ':tropical_drink:', category: 'food' },
  { char: '🍺', name: 'Beer Mug', shortcode: ':beer:', category: 'food' },
  { char: '🍻', name: 'Clinking Beer Mugs', shortcode: ':beers:', category: 'food' },
  { char: '🥂', name: 'Clinking Glasses', shortcode: ':clinking_glasses:', category: 'food' },
  { char: '🥃', name: 'Tumbler Glass', shortcode: ':tumbler_glass:', category: 'food' },
  { char: '🥤', name: 'Cup with Straw', shortcode: ':cup_with_straw:', category: 'food' },
  { char: '🧊', name: 'Ice', shortcode: ':ice_cube:', category: 'food' },

  // Activities & Sports (expanded)
  { char: '⚽', name: 'Soccer Ball', shortcode: ':soccer:', category: 'activities' },
  { char: '🏀', name: 'Basketball', shortcode: ':basketball:', category: 'activities' },
  { char: '🏈', name: 'American Football', shortcode: ':football:', category: 'activities' },
  { char: '⚾', name: 'Baseball', shortcode: ':baseball:', category: 'activities' },
  { char: '🥎', name: 'Softball', shortcode: ':softball:', category: 'activities' },
  { char: '🎾', name: 'Tennis', shortcode: ':tennis:', category: 'activities' },
  { char: '🏐', name: 'Volleyball', shortcode: ':volleyball:', category: 'activities' },
  { char: '🏉', name: 'Rugby Football', shortcode: ':rugby_football:', category: 'activities' },
  { char: '🎱', name: 'Pool 8 Ball', shortcode: ':8ball:', category: 'activities' },
  { char: '🥏', name: 'Flying Disc', shortcode: ':flying_disc:', category: 'activities' },
  { char: '🎳', name: 'Bowling', shortcode: ':bowling:', category: 'activities' },
  { char: '🏏', name: 'Cricket Game', shortcode: ':cricket_game:', category: 'activities' },
  { char: '🏑', name: 'Field Hockey', shortcode: ':field_hockey:', category: 'activities' },
  { char: '🏒', name: 'Ice Hockey', shortcode: ':ice_hockey:', category: 'activities' },
  { char: '🥍', name: 'Lacrosse', shortcode: ':lacrosse:', category: 'activities' },
  { char: '🏓', name: 'Ping Pong', shortcode: ':ping_pong:', category: 'activities' },
  { char: '🏸', name: 'Badminton', shortcode: ':badminton:', category: 'activities' },
  { char: '🥊', name: 'Boxing Glove', shortcode: ':boxing_glove:', category: 'activities' },
  { char: '🥋', name: 'Martial Arts Uniform', shortcode: ':martial_arts_uniform:', category: 'activities' },
  { char: '🥅', name: 'Goal Net', shortcode: ':goal_net:', category: 'activities' },
  { char: '⛳', name: 'Flag in Hole', shortcode: ':golf:', category: 'activities' },
  { char: '⛸️', name: 'Ice Skate', shortcode: ':ice_skate:', category: 'activities' },
  { char: '🎣', name: 'Fishing Pole', shortcode: ':fishing_pole_and_fish:', category: 'activities' },
  { char: '🤿', name: 'Diving Mask', shortcode: ':diving_mask:', category: 'activities' },
  { char: '🎽', name: 'Running Shirt', shortcode: ':running_shirt_with_sash:', category: 'activities' },
  { char: '🎿', name: 'Skis', shortcode: ':ski:', category: 'activities' },
  { char: '⛷️', name: 'Skier', shortcode: ':skier:', category: 'activities' },
  { char: '🏂', name: 'Snowboarder', shortcode: ':snowboarder:', category: 'activities' },
  { char: '🪂', name: 'Parachute', shortcode: ':parachute:', category: 'activities' },
  { char: '🏋️', name: 'Person Lifting Weights', shortcode: ':weight_lifting:', category: 'activities' },
  { char: '🤸', name: 'Person Cartwheeling', shortcode: ':cartwheeling:', category: 'activities' },
  { char: '🤺', name: 'Person Fencing', shortcode: ':fencing:', category: 'activities' },
  { char: '🏇', name: 'Horse Racing', shortcode: ':horse_racing:', category: 'activities' },
  { char: '🏄', name: 'Surfer', shortcode: ':surfer:', category: 'activities' },
  { char: '🏊', name: 'Swimmer', shortcode: ':swimmer:', category: 'activities' },
  { char: '🧗', name: 'Person Climbing', shortcode: ':climbing:', category: 'activities' },
  { char: '🧘', name: 'Person in Lotus Position', shortcode: ':lotus_position:', category: 'activities' },
  { char: '🏆', name: 'Trophy', shortcode: ':trophy:', category: 'activities' },
  { char: '🥇', name: '1st Place Medal', shortcode: ':first_place_medal:', category: 'activities' },
  { char: '🥈', name: '2nd Place Medal', shortcode: ':second_place_medal:', category: 'activities' },
  { char: '🥉', name: '3rd Place Medal', shortcode: ':third_place_medal:', category: 'activities' },
  { char: '🏅', name: 'Sports Medal', shortcode: ':medal:', category: 'activities' },
  { char: '🎖️', name: 'Military Medal', shortcode: ':military_medal:', category: 'activities' },
  { char: '🎗️', name: 'Reminder Ribbon', shortcode: ':reminder_ribbon:', category: 'activities' },
  { char: '🎟️', name: 'Admission Tickets', shortcode: ':ticket:', category: 'activities' },
  { char: '🎪', name: 'Circus Tent', shortcode: ':circus_tent:', category: 'activities' },
  { char: '🎭', name: 'Performing Arts', shortcode: ':performing_arts:', category: 'activities' },
  { char: '🎨', name: 'Artist Palette', shortcode: ':art:', category: 'activities' },
  { char: '🎬', name: 'Clapper Board', shortcode: ':clapper:', category: 'activities' },
  { char: '🎤', name: 'Microphone', shortcode: ':microphone:', category: 'activities' },
  { char: '🎧', name: 'Headphone', shortcode: ':headphones:', category: 'activities' },
  { char: '🎼', name: 'Musical Score', shortcode: ':musical_score:', category: 'activities' },
  { char: '🎹', name: 'Musical Keyboard', shortcode: ':musical_keyboard:', category: 'activities' },
  { char: '🥁', name: 'Drum', shortcode: ':drum:', category: 'activities' },
  { char: '🎷', name: 'Saxophone', shortcode: ':saxophone:', category: 'activities' },
  { char: '🎺', name: 'Trumpet', shortcode: ':trumpet:', category: 'activities' },
  { char: '🎸', name: 'Guitar', shortcode: ':guitar:', category: 'activities' },
  { char: '🎻', name: 'Violin', shortcode: ':violin:', category: 'activities' },
  { char: '🎮', name: 'Video Game', shortcode: ':video_game:', category: 'activities' },
  { char: '🧩', name: 'Jigsaw', shortcode: ':jigsaw:', category: 'activities' },
  { char: '🎲', name: 'Game Die', shortcode: ':game_die:', category: 'activities' },

  // Travel & Transport (expanded)
  { char: '🚗', name: 'Automobile', shortcode: ':car:', category: 'travel' },
  { char: '🚕', name: 'Taxi', shortcode: ':taxi:', category: 'travel' },
  { char: '🚙', name: 'SUV', shortcode: ':blue_car:', category: 'travel' },
  { char: '🚌', name: 'Bus', shortcode: ':bus:', category: 'travel' },
  { char: '🚎', name: 'Trolleybus', shortcode: ':trolleybus:', category: 'travel' },
  { char: '🏎️', name: 'Racing Car', shortcode: ':racing_car:', category: 'travel' },
  { char: '🚓', name: 'Police Car', shortcode: ':police_car:', category: 'travel' },
  { char: '🚑', name: 'Ambulance', shortcode: ':ambulance:', category: 'travel' },
  { char: '🚒', name: 'Fire Engine', shortcode: ':fire_engine:', category: 'travel' },
  { char: '🚐', name: 'Minibus', shortcode: ':minibus:', category: 'travel' },
  { char: '🚚', name: 'Delivery Truck', shortcode: ':truck:', category: 'travel' },
  { char: '🚛', name: 'Articulated Lorry', shortcode: ':articulated_lorry:', category: 'travel' },
  { char: '🚜', name: 'Tractor', shortcode: ':tractor:', category: 'travel' },
  { char: '🛴', name: 'Kick Scooter', shortcode: ':scooter:', category: 'travel' },
  { char: '🚲', name: 'Bicycle', shortcode: ':bicycle:', category: 'travel' },
  { char: '🛵', name: 'Motor Scooter', shortcode: ':motor_scooter:', category: 'travel' },
  { char: '🏍️', name: 'Motorcycle', shortcode: ':motorcycle:', category: 'travel' },
  { char: '🛺', name: 'Auto Rickshaw', shortcode: ':auto_rickshaw:', category: 'travel' },
  { char: '🛹', name: 'Skateboard', shortcode: ':skateboard:', category: 'travel' },
  { char: '🚂', name: 'Locomotive', shortcode: ':steam_locomotive:', category: 'travel' },
  { char: '🚃', name: 'Railway Car', shortcode: ':railway_car:', category: 'travel' },
  { char: '🚆', name: 'Train', shortcode: ':train2:', category: 'travel' },
  { char: '🚅', name: 'High-Speed Train', shortcode: ':bullettrain_front:', category: 'travel' },
  { char: '✈️', name: 'Airplane', shortcode: ':airplane:', category: 'travel' },
  { char: '🛩️', name: 'Small Airplane', shortcode: ':small_airplane:', category: 'travel' },
  { char: '🛫', name: 'Airplane Departure', shortcode: ':airplane_departure:', category: 'travel' },
  { char: '🛬', name: 'Airplane Arrival', shortcode: ':airplane_arriving:', category: 'travel' },
  { char: '🚀', name: 'Rocket', shortcode: ':rocket:', category: 'travel' },
  { char: '🛰️', name: 'Satellite', shortcode: ':satellite:', category: 'travel' },
  { char: '🛸', name: 'Flying Saucer', shortcode: ':flying_saucer:', category: 'travel' },
  { char: '🚁', name: 'Helicopter', shortcode: ':helicopter:', category: 'travel' },
  { char: '⛵', name: 'Sailboat', shortcode: ':sailboat:', category: 'travel' },
  { char: '🚤', name: 'Speedboat', shortcode: ':speedboat:', category: 'travel' },
  { char: '🚢', name: 'Ship', shortcode: ':ship:', category: 'travel' },
  { char: '⚓', name: 'Anchor', shortcode: ':anchor:', category: 'travel' },
  { char: '⛽', name: 'Fuel Pump', shortcode: ':fuelpump:', category: 'travel' },
  { char: '🚧', name: 'Construction', shortcode: ':construction:', category: 'travel' },
  { char: '🚦', name: 'Vertical Traffic Light', shortcode: ':vertical_traffic_light:', category: 'travel' },
  { char: '🗼', name: 'Tokyo Tower', shortcode: ':tokyo_tower:', category: 'travel' },
  { char: '🗽', name: 'Statue of Liberty', shortcode: ':statue_of_liberty:', category: 'travel' },
  { char: '🏰', name: 'Castle', shortcode: ':castle:', category: 'travel' },
  { char: '🏯', name: 'Japanese Castle', shortcode: ':japanese_castle:', category: 'travel' },
  { char: '🏟️', name: 'Stadium', shortcode: ':stadium:', category: 'travel' },
  { char: '🎡', name: 'Ferris Wheel', shortcode: ':ferris_wheel:', category: 'travel' },
  { char: '🎢', name: 'Roller Coaster', shortcode: ':roller_coaster:', category: 'travel' },
  { char: '🎠', name: 'Carousel Horse', shortcode: ':carousel_horse:', category: 'travel' },
  { char: '⛲', name: 'Fountain', shortcode: ':fountain:', category: 'travel' },
  { char: '🏖️', name: 'Beach with Umbrella', shortcode: ':beach_with_umbrella:', category: 'travel' },
  { char: '⛰️', name: 'Mountain', shortcode: ':mountain:', category: 'travel' },
  { char: '🏕️', name: 'Camping', shortcode: ':camping:', category: 'travel' },
  { char: '🏠', name: 'House', shortcode: ':house:', category: 'travel' },
  { char: '🏢', name: 'Office Building', shortcode: ':office:', category: 'travel' },
  { char: '🏥', name: 'Hospital', shortcode: ':hospital:', category: 'travel' },
  { char: '🏦', name: 'Bank', shortcode: ':bank:', category: 'travel' },
  { char: '🏫', name: 'School', shortcode: ':school:', category: 'travel' },
  { char: '🗺️', name: 'World Map', shortcode: ':world_map:', category: 'travel' },

  // Objects & Tools (expanded)
  { char: '⌚', name: 'Watch', shortcode: ':watch:', category: 'objects' },
  { char: '📱', name: 'Mobile Phone', shortcode: ':iphone:', category: 'objects' },
  { char: '💻', name: 'Laptop', shortcode: ':computer:', category: 'objects' },
  { char: '⌨️', name: 'Keyboard', shortcode: ':keyboard:', category: 'objects' },
  { char: '🖥️', name: 'Desktop Computer', shortcode: ':desktop_computer:', category: 'objects' },
  { char: '🖨️', name: 'Printer', shortcode: ':printer:', category: 'objects' },
  { char: '🖱️', name: 'Computer Mouse', shortcode: ':computer_mouse:', category: 'objects' },
  { char: '📷', name: 'Camera', shortcode: ':camera:', category: 'objects' },
  { char: '📸', name: 'Camera with Flash', shortcode: ':camera_flash:', category: 'objects' },
  { char: '📺', name: 'Television', shortcode: ':tv:', category: 'objects' },
  { char: '💡', name: 'Light Bulb', shortcode: ':bulb:', category: 'objects' },
  { char: '🔦', name: 'Flashlight', shortcode: ':flashlight:', category: 'objects' },
  { char: '🕯️', name: 'Candle', shortcode: ':candle:', category: 'objects' },
  { char: '🔌', name: 'Electric Plug', shortcode: ':electric_plug:', category: 'objects' },
  { char: '🔋', name: 'Battery', shortcode: ':battery:', category: 'objects' },
  { char: '💰', name: 'Money Bag', shortcode: ':moneybag:', category: 'objects' },
  { char: '💳', name: 'Credit Card', shortcode: ':credit_card:', category: 'objects' },
  { char: '💎', name: 'Gem Stone', shortcode: ':gem:', category: 'objects' },
  { char: '🔫', name: 'Pistol', shortcode: ':gun:', category: 'objects' },
  { char: '💣', name: 'Bomb', shortcode: ':bomb:', category: 'objects' },
  { char: '🔪', name: 'Kitchen Knife', shortcode: ':hocho:', category: 'objects' },
  { char: '🛡️', name: 'Shield', shortcode: ':shield:', category: 'objects' },
  { char: '🔧', name: 'Wrench', shortcode: ':wrench:', category: 'objects' },
  { char: '🔨', name: 'Hammer', shortcode: ':hammer:', category: 'objects' },
  { char: '🔩', name: 'Nut and Bolt', shortcode: ':nut_and_bolt:', category: 'objects' },
  { char: '⚙️', name: 'Gear', shortcode: ':gear:', category: 'objects' },
  { char: '⛓️', name: 'Chains', shortcode: ':chains:', category: 'objects' },
  { char: '⚰️', name: 'Coffin', shortcode: ':coffin:', category: 'objects' },
  { char: '🔬', name: 'Microscope', shortcode: ':microscope:', category: 'objects' },
  { char: '🔭', name: 'Telescope', shortcode: ':telescope:', category: 'objects' },
  { char: '💊', name: 'Pill', shortcode: ':pill:', category: 'objects' },
  { char: '💉', name: 'Syringe', shortcode: ':syringe:', category: 'objects' },
  { char: '🩸', name: 'Drop of Blood', shortcode: ':drop_of_blood:', category: 'objects' },
  { char: '🚽', name: 'Toilet', shortcode: ':toilet:', category: 'objects' },
  { char: '🚿', name: 'Shower', shortcode: ':shower:', category: 'objects' },
  { char: '🔑', name: 'Key', shortcode: ':key:', category: 'objects' },
  { char: '🔐', name: 'Locked with Key', shortcode: ':closed_lock_with_key:', category: 'objects' },
  { char: '🔒', name: 'Locked', shortcode: ':lock:', category: 'objects' },
  { char: '🔓', name: 'Unlocked', shortcode: ':unlock:', category: 'objects' },
  { char: '🔔', name: 'Bell', shortcode: ':bell:', category: 'objects' },
  { char: '📚', name: 'Books', shortcode: ':books:', category: 'objects' },
  { char: '📖', name: 'Open Book', shortcode: ':book:', category: 'objects' },
  { char: '🔖', name: 'Bookmark', shortcode: ':bookmark:', category: 'objects' },
  { char: '📎', name: 'Paperclip', shortcode: ':paperclip:', category: 'objects' },
  { char: '✏️', name: 'Pencil', shortcode: ':pencil2:', category: 'objects' },
  { char: '🖊️', name: 'Pen', shortcode: ':pen:', category: 'objects' },
  { char: '✒️', name: 'Black Nib', shortcode: ':black_nib:', category: 'objects' },
  { char: '✂️', name: 'Scissors', shortcode: ':scissors:', category: 'objects' },
  { char: '📌', name: 'Pushpin', shortcode: ':pushpin:', category: 'objects' },
  { char: '📏', name: 'Straight Ruler', shortcode: ':straight_ruler:', category: 'objects' },
  { char: '📐', name: 'Triangular Ruler', shortcode: ':triangular_ruler:', category: 'objects' },
  { char: '🗑️', name: 'Wastebasket', shortcode: ':wastebasket:', category: 'objects' },
  { char: '👑', name: 'Crown', shortcode: ':crown:', category: 'objects' },
  { char: '🎩', name: 'Top Hat', shortcode: ':tophat:', category: 'objects' },
  { char: '🎓', name: 'Graduation Cap', shortcode: ':mortar_board:', category: 'objects' },
  { char: '👓', name: 'Glasses', shortcode: ':eyeglasses:', category: 'objects' },
  { char: '👔', name: 'Necktie', shortcode: ':necktie:', category: 'objects' },
  { char: '👕', name: 'T-Shirt', shortcode: ':shirt:', category: 'objects' },
  { char: '👖', name: 'Jeans', shortcode: ':jeans:', category: 'objects' },
  { char: '👗', name: 'Dress', shortcode: ':dress:', category: 'objects' },
  { char: '👘', name: 'Kimono', shortcode: ':kimono:', category: 'objects' },
  { char: '👙', name: 'Bikini', shortcode: ':bikini:', category: 'objects' },
  { char: '👠', name: 'High-Heeled Shoe', shortcode: ':high_heel:', category: 'objects' },
  { char: '👟', name: 'Running Shoe', shortcode: ':athletic_shoe:', category: 'objects' },
  { char: '👜', name: 'Handbag', shortcode: ':handbag:', category: 'objects' },
  { char: '🎒', name: 'Backpack', shortcode: ':school_satchel:', category: 'objects' },
  { char: '🧭', name: 'Compass', shortcode: ':compass:', category: 'objects' },

  // Symbols (expanded)
  { char: '❤️', name: 'Red Heart', shortcode: ':heart:', category: 'symbols' },
  { char: '🧡', name: 'Orange Heart', shortcode: ':orange_heart:', category: 'symbols' },
  { char: '💛', name: 'Yellow Heart', shortcode: ':yellow_heart:', category: 'symbols' },
  { char: '💚', name: 'Green Heart', shortcode: ':green_heart:', category: 'symbols' },
  { char: '💙', name: 'Blue Heart', shortcode: ':blue_heart:', category: 'symbols' },
  { char: '💜', name: 'Purple Heart', shortcode: ':purple_heart:', category: 'symbols' },
  { char: '🖤', name: 'Black Heart', shortcode: ':black_heart:', category: 'symbols' },
  { char: '💔', name: 'Broken Heart', shortcode: ':broken_heart:', category: 'symbols' },
  { char: '❣️', name: 'Heart Exclamation', shortcode: ':heavy_heart_exclamation:', category: 'symbols' },
  { char: '💕', name: 'Two Hearts', shortcode: ':two_hearts:', category: 'symbols' },
  { char: '💞', name: 'Revolving Hearts', shortcode: ':revolving_hearts:', category: 'symbols' },
  { char: '💓', name: 'Beating Heart', shortcode: ':heartbeat:', category: 'symbols' },
  { char: '💗', name: 'Growing Heart', shortcode: ':heartpulse:', category: 'symbols' },
  { char: '💖', name: 'Sparkling Heart', shortcode: ':sparkling_heart:', category: 'symbols' },
  { char: '💘', name: 'Heart with Arrow', shortcode: ':cupid:', category: 'symbols' },
  { char: '💌', name: 'Love Letter', shortcode: ':love_letter:', category: 'symbols' },
  { char: '💯', name: 'Hundred Points', shortcode: ':100:', category: 'symbols' },
  { char: '💥', name: 'Collision', shortcode: ':boom:', category: 'symbols' },
  { char: '💫', name: 'Dizzy', shortcode: ':dizzy:', category: 'symbols' },
  { char: '💦', name: 'Sweat Droplets', shortcode: ':sweat_drops:', category: 'symbols' },
  { char: '💨', name: 'Dashing Away', shortcode: ':dash:', category: 'symbols' },
  { char: '💢', name: 'Anger Symbol', shortcode: ':anger:', category: 'symbols' },
  { char: '💬', name: 'Speech Balloon', shortcode: ':speech_balloon:', category: 'symbols' },
  { char: '💤', name: 'Zzz', shortcode: ':zzz:', category: 'symbols' },
  { char: '✅', name: 'Check Mark Button', shortcode: ':white_check_mark:', category: 'symbols' },
  { char: '✔️', name: 'Check Mark', shortcode: ':heavy_check_mark:', category: 'symbols' },
  { char: '❌', name: 'Cross Mark', shortcode: ':x:', category: 'symbols' },
  { char: '🚫', name: 'Prohibited', shortcode: ':no_entry_sign:', category: 'symbols' },
  { char: '❓', name: 'Question Mark', shortcode: ':question:', category: 'symbols' },
  { char: '❔', name: 'White Question Mark', shortcode: ':grey_question:', category: 'symbols' },
  { char: '❕', name: 'White Exclamation Mark', shortcode: ':grey_exclamation:', category: 'symbols' },
  { char: '❗', name: 'Exclamation Mark', shortcode: ':exclamation:', category: 'symbols' },
  { char: '⚠️', name: 'Warning', shortcode: ':warning:', category: 'symbols' },
  { char: '➕', name: 'Plus', shortcode: ':heavy_plus_sign:', category: 'symbols' },
  { char: '➖', name: 'Minus', shortcode: ':heavy_minus_sign:', category: 'symbols' },
  { char: '➗', name: 'Division', shortcode: ':heavy_division_sign:', category: 'symbols' },
  { char: '✖️', name: 'Multiplication', shortcode: ':heavy_multiplication_x:', category: 'symbols' },
  { char: '💲', name: 'Heavy Dollar Sign', shortcode: ':heavy_dollar_sign:', category: 'symbols' },
  { char: '™️', name: 'Trade Mark', shortcode: ':tm:', category: 'symbols' },
  { char: '©️', name: 'Copyright', shortcode: ':copyright:', category: 'symbols' },
  { char: '®️', name: 'Registered', shortcode: ':registered:', category: 'symbols' },
  { char: '🔘', name: 'Radio Button', shortcode: ':radio_button:', category: 'symbols' },
  { char: '⚫', name: 'Black Circle', shortcode: ':black_circle:', category: 'symbols' },
  { char: '🔴', name: 'Red Circle', shortcode: ':red_circle:', category: 'symbols' },
  { char: '✨', name: 'Sparkles', shortcode: ':sparkles:', category: 'symbols' },

  // Flags (expanded subset)
  { char: '🏁', name: 'Chequered Flag', shortcode: ':checkered_flag:', category: 'flags' },
  { char: '🚩', name: 'Triangular Flag', shortcode: ':triangular_flag_on_post:', category: 'flags' },
  { char: '🎌', name: 'Crossed Flags', shortcode: ':crossed_flags:', category: 'flags' },
  { char: '🏳️‍🌈', name: 'Rainbow Flag', shortcode: ':rainbow_flag:', category: 'flags' },
  { char: '🇦🇺', name: 'Flag: Australia', shortcode: ':flag-au:', category: 'flags' },
  { char: '🇧🇷', name: 'Flag: Brazil', shortcode: ':flag-br:', category: 'flags' },
  { char: '🇨🇦', name: 'Flag: Canada', shortcode: ':flag-ca:', category: 'flags' },
  { char: '🇨🇳', name: 'Flag: China', shortcode: ':flag-cn:', category: 'flags' },
  { char: '🇫🇷', name: 'Flag: France', shortcode: ':flag-fr:', category: 'flags' },
  { char: '🇩🇪', name: 'Flag: Germany', shortcode: ':flag-de:', category: 'flags' },
  { char: '🇮🇳', name: 'Flag: India', shortcode: ':flag-in:', category: 'flags' },
  { char: '🇮🇹', name: 'Flag: Italy', shortcode: ':flag-it:', category: 'flags' },
  { char: '🇯🇵', name: 'Flag: Japan', shortcode: ':flag-jp:', category: 'flags' },
  { char: '🇲🇽', name: 'Flag: Mexico', shortcode: ':flag-mx:', category: 'flags' },
  { char: '🇵🇭', name: 'Flag: Philippines', shortcode: ':flag-ph:', category: 'flags' },
  { char: '🇷🇺', name: 'Flag: Russia', shortcode: ':flag-ru:', category: 'flags' },
  { char: '🇿🇦', name: 'Flag: South Africa', shortcode: ':flag-za:', category: 'flags' },
  { char: '🇰🇷', name: 'Flag: South Korea', shortcode: ':flag-kr:', category: 'flags' },
  { char: '🇪🇸', name: 'Flag: Spain', shortcode: ':flag-es:', category: 'flags' },
  { char: '🇬🇧', name: 'Flag: United Kingdom', shortcode: ':flag-gb:', category: 'flags' },
  { char: '🇺🇸', name: 'Flag: United States', shortcode: ':flag-us:', category: 'flags' },
]

export default STATIC_EMOJIS

// Runtime loader for the full emoji dataset.
// Tries (in order):
//  1) dynamic import of `emoji-datasource-apple` (already listed in package.json),
//  2) fetching `/emoji-full.json` from `public/` (user can place a full JSON there),
//  3) fallback to the curated STATIC_EMOJIS above.
export async function loadFullEmojiList(): Promise<EmojiStatic[]> {
  // helper: convert unified hex (e.g. "1F600" or "1F1FA-1F1F8") to characters
  function unifiedToChar(u: string | undefined, fallback?: string) {
    if (!u) return fallback || ''
    try {
      return String.fromCodePoint(...u.split('-').map(s => parseInt(s, 16)))
    } catch {
      return fallback || ''
    }
  }

  // 1) try dynamic import from emoji-datasource-apple
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const mod = await import('emoji-datasource-apple')
    const data = (mod && (mod.default || mod)) as any[]
    if (Array.isArray(data) && data.length) {
      const mapped = data.map(item => {
        const char = item.emoji || unifiedToChar(item.unified, item.emoji)
        const name = item.name || item.short_name || (item.short_names && item.short_names[0]) || char
        const shortcode = item.short_name ? `:${item.short_name}:` : (item.short_names && item.short_names[0] ? `:${item.short_names[0]}:` : '')
        const category = item.category ? String(item.category).toLowerCase() : undefined
        const keywords = item.keywords || item.short_names || []
        return { char, name, shortcode, category, keywords } as EmojiStatic
      })
      return mapped
    }
  } catch (e) {
    // module may not be available in some environments; silently continue to next option
  }

  // 2) try fetching a JSON file from public/emoji-full.json
  try {
    if (typeof fetch === 'function') {
      const res = await fetch('/emoji-full.json')
      if (res.ok) {
        const data = await res.json()
        if (Array.isArray(data)) return data as EmojiStatic[]
      }
    }
  } catch (_) { /* ignore fetch errors */ }

  // 3) fallback to curated list
  return STATIC_EMOJIS
}